{
  "hash": "fe09b73ae27505e6c08715af552f57a3",
  "result": {
    "markdown": "---\ntitle: \"Les données\"\ntitle-block-banner: true\ndescription: | \n  Cette page regroupe la première importation des données ainsi que les manipulation de bases.\n# à changer\ndate: \"2022-12-21\"\n# Modifier les détails que vous voulez\nauthor:\n  - name: \"Amy Vallières\"\n    # Votre site web perso ou github\n    url: https://github.com/VOTREUSERNAME\n    # les champs d'affiliation sont optionnels, vous pouvez les\n    # comment out en ajoutant un # devant.\n    affiliation: FAS1002\n    affiliation-url: https://FAS1002.github.io/A22\n    # changer pour votre propre orcid id\n    # https://orcid.org/ pour vous inscrire.\n    orcid: 0000-0000-0000-0000\n\n# TRUE == Générer une citation pour cette page précise. Pour enlever, mettre false.\ncitation: true\n# Inclure les références que vous utilisez dans vos rapports. Je conseille Zotero pour construire\n# ce fichier ou de connecter RStudio directement pour pouvoir citer avec @nom-de-reference.\nbibliography: references.bib\n---\n\n\nIl est maintenant le temps de décrire votre projet avant de passer au document suivant, soit l'importation et la manipulation des données.\n\nJe vous conseille d'écrire cette partie en dernier, une fois que vous aurez déjà vos résultats et figures afin d'éviter de réécrire cette page plusieurs fois.\n\n::: callout-important\nN'oubliez pas d'inclure vos références sur chacune des pages!\n:::\n\nPar exemple:\n\n> Les données proviennent entre autres de @owidenergy.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.5.0 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(fs)\nlibrary(lubridate)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLe chargement a nécessité le package : timechange\n\nAttachement du package : 'lubridate'\n\nLes objets suivants sont masqués depuis 'package:base':\n\n    date, intersect, setdiff, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(skimr)\nlibrary(countrycode)\nlibrary(gsheet)\nlibrary(httr)\n```\n:::\n\n\n## Importer les données\n\n### Les données *Our World in Data*\n\nJ'utilise en premier la banque de données du *Co2 and Greenhouse Gaz Emissions*. Mise à jour tous les jours.\n\nLes données proviennent de : https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(\"helper.R\")\ndata_co2 <- get_raw_data()\n```\n:::\n\n\n### Données gapminder\n\nPour la deuxième banque de données, je fais appel à celle produite par *Gapminder* qui se nomme *Life Expectancy at Birth*. Celle-ci seront re-téléchargé pour une mise à jour à tous les mois.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nurl_gapminder <-  \"https://docs.google.com/spreadsheets/d/1RheSon1-q4vFc3AGyupVPH6ptEByE-VtnjOCselU0PE/edit#gid=176703676\"\nsheet_gapminder <- gsheet2tbl(url_gapminder)\nbase_path <- path(\"data\", \"raw\")\nfname_gap <- paste(today(), \"gapm.csv\", sep = \"_\")\nfpath_gap <- path(base_path, fname_gap)\nwrite.csv(sheet_gapminder, \"sheet_gapminder.csv\")\n```\n:::\n\n\n### Création d'une variable\n\nNous allons créer la variable continent pour les deux banques de données pour faciliter les analyses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_co2 <- data_co2 |> \n    mutate(continent = countrycode(sourcevar = data_co2$country,\n                                   origin = \"country.name\",\n                                   destination = \"continent\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in countrycode_convert(sourcevar = sourcevar, origin = origin, destination = dest, : Some values were not matched unambiguously: Africa, Africa (GCP), Antarctica, Asia, Asia (excl. China and India), Asia (GCP), Central America (GCP), Europe, Europe (excl. EU-27), Europe (excl. EU-28), Europe (GCP), European Union (27), European Union (27) (GCP), European Union (28), French Equatorial Africa (GCP), French West Africa (GCP), High-income countries, International transport, Kosovo, Leeward Islands (GCP), Low-income countries, Lower-middle-income countries, Micronesia (country), Middle East (GCP), Non-OECD (GCP), North America, North America (GCP), Oceania, Oceania (GCP), OECD (GCP), Ryukyu Islands (GCP), South America, South America (GCP), St. Kitts-Nevis-Anguilla (GCP), Timor, Upper-middle-income countries, World\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in countrycode_convert(sourcevar = sourcevar, origin = origin, destination = dest, : Some strings were matched more than once, and therefore set to <NA> in the result: Asia (excl. China and India),Asia,Asia; St. Kitts-Nevis-Anguilla (GCP),Americas,Americas\n```\n:::\n\n```{.r .cell-code}\nsheet_gapminder <- sheet_gapminder |> \n    mutate(continent = countrycode(sourcevar = sheet_gapminder$name,\n                                   origin = \"country.name\",\n                                   destination = \"continent\"))\n```\n:::\n\n\n### Recoder les variables\n\nLes variables des deux banques de données n'ont pas le même nom, on va donc changer la variable *name* de gapminder par *country*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsheet_gapminder <- sheet_gapminder |> \n    rename(country = name,\n           year = time)\n```\n:::\n\n\n## Exporter les données\n\nExporter les données qui sont traités dans le dossier data/processed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_csv(data_co2,file = \"data/processed/data_co2.csv\")\nwrite_csv(sheet_gapminder, file = \"data/processed/sheet_gapminder.csv\")\n```\n:::\n\n\n## \n\n## Manipulation des données\n\nLa base de données *Co2 and Greenhouse Gaz Emissions* contient un total de 46523 observations ainsi que 74 variables, avant l'ajout de la variable continent. Cette base de données permet de mieux comprendre les soucres d'énergies et leur consommation dans un total de 207 pays.\n\nDans le but d'obtenir une lecture plus intéressante ainsi qu'une analyse des données, il est plus simple de traiter la base de données avec quelques variables sélectionnés et non pas dans sa totalité. Pour se faire, 18 variables sont sélectionnées.\n\nMais avant, pour faciliter les autres analyses, on va transformer les données en tibble :avec les 18 variables choisies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas.tibble(data_co2)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: `as.tibble()` was deprecated in tibble 2.0.0.\nℹ Please use `as_tibble()` instead.\nℹ The signature and semantics have changed, see `?as_tibble`.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 46,523 × 75\n   country      year iso_c…¹ popul…²   gdp cemen…³ cemen…⁴   co2 co2_g…⁵ co2_g…⁶\n   <chr>       <int> <chr>     <dbl> <dbl>   <dbl>   <dbl> <dbl>   <dbl>   <dbl>\n 1 Afghanistan  1850 AFG     3752993    NA      NA      NA    NA      NA      NA\n 2 Afghanistan  1851 AFG     3769828    NA      NA      NA    NA      NA      NA\n 3 Afghanistan  1852 AFG     3787706    NA      NA      NA    NA      NA      NA\n 4 Afghanistan  1853 AFG     3806634    NA      NA      NA    NA      NA      NA\n 5 Afghanistan  1854 AFG     3825655    NA      NA      NA    NA      NA      NA\n 6 Afghanistan  1855 AFG     3844769    NA      NA      NA    NA      NA      NA\n 7 Afghanistan  1856 AFG     3863976    NA      NA      NA    NA      NA      NA\n 8 Afghanistan  1857 AFG     3883276    NA      NA      NA    NA      NA      NA\n 9 Afghanistan  1858 AFG     3902671    NA      NA      NA    NA      NA      NA\n10 Afghanistan  1859 AFG     3922160    NA      NA      NA    NA      NA      NA\n# … with 46,513 more rows, 65 more variables: co2_including_luc <dbl>,\n#   co2_including_luc_growth_abs <dbl>, co2_including_luc_growth_prct <dbl>,\n#   co2_including_luc_per_capita <dbl>, co2_including_luc_per_gdp <dbl>,\n#   co2_including_luc_per_unit_energy <dbl>, co2_per_capita <dbl>,\n#   co2_per_gdp <dbl>, co2_per_unit_energy <dbl>, coal_co2 <dbl>,\n#   coal_co2_per_capita <dbl>, consumption_co2 <dbl>,\n#   consumption_co2_per_capita <dbl>, consumption_co2_per_gdp <dbl>, …\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_co2 = data_co2 %>% \n    select(country, year, iso_code, population, gdp, co2, cement_co2_per_capita, \n           co2_per_gdp, coal_co2, coal_co2_per_capita, gas_co2, gas_co2_per_capita,\n           methane, methane_per_capita, oil_co2, oil_co2_per_capita, ghg_per_capita, trade_co2)\n```\n:::\n\n\nVoici un tableau qui présente un codebook adapté du codebook original (https://github.com/owid/co2-data/blob/master/owid-co2-codebook.csv) dans le but de mieux comprendre les 18 variables choisies.\n\n| Variables             | Description + Type                                                                                                                                                                                                                                        |\n|-----------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|\n|                       |                                                                                                                                                                                                                                                           |\n| Country               | pays (character)                                                                                                                                                                                                                                          |\n| Year                  | année de l'observation (numérique)                                                                                                                                                                                                                        |\n| Iso_code              | code du pays selon la codification internationale 3166-1 (character)                                                                                                                                                                                      |\n| Population            | Nombre total de la population selon le pays (numérique)                                                                                                                                                                                                   |\n| GDP (PIB)             | Produit interieur brut mesuré en dollars (numérique)                                                                                                                                                                                                      |\n| CO2                   | Mesure annuelle de la production totale de CO2 par pays, mesuré en en millions de tonnes et excluant l'\\[UTCATF\\](https://fr.wikipedia.org/wiki/Utilisation_des_terres,\\_changement_d'affectation_des_terres_et_foresterie) (numérique)                   |\n| Cement_CO2_per_capita | Mesure annuelle de la production totale de CO2 générée par le ciment, par personne, en millions de tonnes (numérique)                                                                                                                                     |\n| CO2_per_gdp           | Mesure annuelle de la production totale de CO2 selon le PIB, excluant l'UTCATF (numérique)                                                                                                                                                                |\n| coal_co2              | Mesure annuelle par pays de la production de CO2 générée par le charbon, en millions de tonnes (numérique)                                                                                                                                                |\n| coal_co2_per_capita   | Mesure annuelle de la production de CO2 générée par le charbon, mesurée en million de tonnes par personnes (numérique)                                                                                                                                    |\n| methane               | Total annuel des émissions de méthane par pays, incluant l'UTCATF, mesuré en millions de tonnes (numérique)                                                                                                                                               |\n| methane_per_capita    | Total annuel des émissions de méthane par habitant, incluant l'UTCATF, mesuré en millions de tonnes (numérique)                                                                                                                                           |\n| oil_co2               | Mesure annuelle par pays de la production de CO2 générée par le pétrole, en millions de tonnes (numérique)                                                                                                                                                |\n| oil_co2_per_capita    | Mesure annuelle de la production de CO2 générée par le pétrole, mesurée en million de tonnes par personnes (numérique) \\|                                                                                                                                 |\n|                       | \\| ghg_per_capita \\| Total des émissions de gas à effet de serres par personne, mesuré en tonne de de millions, incluant l'UTCATF (numérique)                                                                                                             |\n| trade_co2             | Total annuel des émissions de C02, issu du commerce, mesuré en million de tonne. (Ici une valeur positive veut dire qu'un pays est un importeur net d'émission de CO2 ; une valeur négative veut dire qu'un pays est un exporteur net d'émission de CO2). |\n\n### Analyse des données descriptives\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(dat_co2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   country               year        iso_code           population       \n Length:46523       Min.   :1750   Length:46523       Min.   :2.100e+01  \n Class :character   1st Qu.:1882   Class :character   1st Qu.:3.809e+05  \n Mode  :character   Median :1930   Mode  :character   Median :2.509e+06  \n                    Mean   :1926                      Mean   :6.005e+07  \n                    3rd Qu.:1977                      3rd Qu.:9.996e+06  \n                    Max.   :2021                      Max.   :7.909e+09  \n                                                      NA's   :7949       \n      gdp                 co2           cement_co2_per_capita  co2_per_gdp    \n Min.   :4.998e+07   Min.   :    0.00   Min.   :0.000         Min.   : 0.000  \n 1st Qu.:7.530e+09   1st Qu.:    0.12   1st Qu.:0.000         1st Qu.: 0.135  \n Median :2.606e+10   Median :    3.11   Median :0.005         Median : 0.275  \n Mean   :2.680e+11   Mean   :  379.99   Mean   :0.064         Mean   : 0.418  \n 3rd Qu.:1.135e+11   3rd Qu.:   43.66   3rd Qu.:0.087         3rd Qu.: 0.532  \n Max.   :1.136e+14   Max.   :37123.85   Max.   :2.574         Max.   :37.608  \n NA's   :31972       NA's   :15174      NA's   :23809         NA's   :30232   \n    coal_co2         coal_co2_per_capita    gas_co2         gas_co2_per_capita\n Min.   :    0.000   Min.   : 0.000      Min.   :   0.000   Min.   : 0.000    \n 1st Qu.:    0.000   1st Qu.: 0.000      1st Qu.:   0.000   1st Qu.: 0.000    \n Median :    0.655   Median : 0.088      Median :   0.000   Median : 0.000    \n Mean   :  154.396   Mean   : 1.096      Mean   :  49.985   Mean   : 0.528    \n 3rd Qu.:   16.484   3rd Qu.: 1.139      3rd Qu.:   1.238   3rd Qu.: 0.081    \n Max.   :15051.513   Max.   :34.229      Max.   :7921.830   Max.   :53.311    \n NA's   :21454       NA's   :22102       NA's   :21580      NA's   :22183     \n    methane        methane_per_capita    oil_co2          oil_co2_per_capita\n Min.   :   0.00   Min.   : 0.00      Min.   :    0.000   Min.   :  0.000   \n 1st Qu.:   2.11   1st Qu.: 0.68      1st Qu.:    0.077   1st Qu.:  0.040   \n Median :   9.43   Median : 1.05      Median :    1.235   Median :  0.385   \n Mean   : 145.65   Mean   : 1.84      Mean   :  111.227   Mean   :  2.204   \n 3rd Qu.:  37.66   3rd Qu.: 1.75      3rd Qu.:   13.102   3rd Qu.:  1.972   \n Max.   :8609.92   Max.   :33.68      Max.   :12345.653   Max.   :824.457   \n NA's   :40373     NA's   :40403      NA's   :21481       NA's   :22156     \n ghg_per_capita     trade_co2       \n Min.   :-30.81   Min.   :-2354.78  \n 1st Qu.:  2.57   1st Qu.:   -3.15  \n Median :  5.42   Median :    1.48  \n Mean   :  7.54   Mean   :   -8.70  \n 3rd Qu.:  9.86   3rd Qu.:    9.03  \n Max.   : 73.67   Max.   : 2211.85  \n NA's   :40404    NA's   :42264     \n```\n:::\n:::\n\n\n-   Les données comprennent des informations sur la population, le PIB, les émissions de CO2 et d'autres gaz à effet de serre, ainsi que les émissions de ciment pour 46523 pays à différentes années allant de 1750 à 2021.\n\n-   Certaines données sont manquantes pour certains pays et certaines années, avec un nombre important de valeurs manquantes pour les colonnes liées aux émissions de CO2 et aux autres gaz à effet de serre.\n\n-   La population varie considérablement entre les pays, avec des valeurs allant de 21 à 790 millions d'habitants. Le PIB varie également considérablement, avec des valeurs allant de 4,998 milliards à 1136 trillions de dollars.\n\n-   Les émissions de CO2 varient considérablement entre les pays et les années, avec des valeurs allant de 0 à 37123,85 millions de tonnes. Les émissions de ciment par habitant varient également, avec des valeurs allant de 0 à 2,574 tonnes par habitant.\n\n-   Les autres colonnes liées aux émissions de gaz à effet de serre présentent également une grande variabilité. Par exemple, les émissions de charbon varient de 0 à 15051,513 millions de tonnes, les émissions de gaz varient de 0 à 7921,830 millions de tonnes et les émissions de méthane varient de 0 à 8609,92 millions de tonnes.\n\n-   Les émissions de gaz à effet de serre par habitant varient de -30,81 à 53,311 tonnes par habitant, tandis que les émissions liées aux échanges commerciaux varient de -2354,78 à 2386,68 millions de tonnes.\n\n## Combiner les deux banques de données\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmerged_data <- dplyr::inner_join(data_co2, sheet_gapminder) %>%\n  arrange(iso_code, year, country)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nJoining, by = c(\"country\", \"year\", \"continent\")\n```\n:::\n:::\n\n\n#### \n\nCréer un csv pour les données\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite.csv(merged_data, \"data/raw/merged_data.csv\", row.names=FALSE)\n```\n:::\n\n\n#### \n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}